# Use a lightweight Node.js image as the base
FROM node:21.7.1-alpine 

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy only package.json and package-lock.json to leverage Docker layer caching for dependencies
COPY package*json ./

# Copy Sequelize configuration
COPY .sequelizerc ./ 

# Install dependencies (development mode)
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port your app runs on
EXPOSE 8000

# Default command to start the application in development mode
CMD ["npm", "run", "dev"]